import { useEffect, useState } from 'react';
import { useParams, Link }    from 'react-router-dom';
import type { ReadingMaterials } from '../types';
import { LoadingSpinner }         from './LoadingSpinner';
import { ErrorBanner }            from './ErrorBanner';
import { TableOfContents }        from './TableOfContents';
import { SectionBlock }           from './SectionBlock';
import { GlossarySection }        from './GlossarySection';
import { DiscussionQuestions }    from './DiscussionQuestions';
import { FurtherReading }         from './FurtherReading';

export function ReadingView() {
    const { docket } = useParams<{ docket: string }>();
    const [rm,      setRm]      = useState<ReadingMaterials | null>(null);
    const [loading, setLoading] = useState(true);
    const [error,   setError]   = useState<string | null>(null);
    const [polling, setPolling] = useState(false);

    useEffect(() => {
        if (!docket) return;

        let cancelled = false;
        const encodedDocket = encodeURIComponent(docket);

        async function load() {
            try {
                const r = await fetch(
                    `/api/opinions/${encodedDocket}/reading`,
                    { headers: { Accept: 'application/json' } },
                );

                if (cancelled) return;

                if (r.status === 202) {
                    // Opinion is being processed — poll every 10 s
                    setLoading(false);
                    setPolling(true);
                    setTimeout(() => { if (!cancelled) { setPolling(false); setLoading(true); load(); } }, 10_000);
                    return;
                }

                if (!r.ok) {
                    const body = await r.json().catch(() => ({})) as { error?: string };
                    setError(body.error ?? `HTTP ${r.status}`);
                    setLoading(false);
                    return;
                }

                const data = await r.json() as ReadingMaterials;
                setRm(data);
                setLoading(false);
            } catch (e) {
                if (!cancelled) { setError(String((e as Error).message)); setLoading(false); }
            }
        }

        load();
        return () => { cancelled = true; };
    }, [docket]);

    if (loading) return <LoadingSpinner />;
    if (polling) {
        return (
            <div className="reading-processing">
                <LoadingSpinner />
                <p className="processing-note">Reading materials are being prepared — checking back shortly…</p>
            </div>
        );
    }
    if (error) return <ErrorBanner message={error} />;
    if (!rm)   return <ErrorBanner message="Reading materials not found." />;

    const date = rm.decided_date
        ? new Date(rm.decided_date).toLocaleDateString('en-US', {
              year: 'numeric', month: 'long', day: 'numeric',
          })
        : null;

    return (
        <article className="reading-view">
            <Link to="/" className="back-link" aria-label="Back to opinion list">
                ← All opinions
            </Link>

            <header className="reading-header">
                <div className="reading-docket">{rm.docket}</div>
                <h1 className="reading-title">{rm.title}</h1>
                {date && <time className="reading-date">{date}</time>}
            </header>

            <TableOfContents sections={rm.sections} />

            <div className="reading-sections">
                {rm.sections.map((s, i) => <SectionBlock key={i} section={s} index={i} />)}
            </div>

            <GlossarySection       entries={rm.glossary} />
            <DiscussionQuestions   questions={rm.discussion_questions} />
            <FurtherReading        entries={rm.further_reading} />

            <p className="reading-disclaimer">
                These reading materials are generated by AI for educational purposes only
                and are not legal advice. ELINAL is not a substitute for qualified counsel.
            </p>
        </article>
    );
}
