name              = "the-locator"
main              = "src/index.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "LOCATOR_CACHE"
id      = "f66140dfbcec4118a44591cc9467cf8e"

[[routes]]
pattern   = "locator.zyxwonderland.xyz/*"
zone_name = "zyxwonderland.xyz"

[assets]
directory          = "../client/dist"
not_found_handling = "single-page-application"
run_worker_first   = true

[vars]
ACS_YEAR    = "2022"
SITE_ORIGIN = "https://zyxwonderland.xyz"
