// ═══════════════════════════════════════════════════════════════════
//  FIREBASE CONFIG — template / example
//
//  In production this file is generated by the GitHub Actions deploy
//  workflow from repository secrets. firebase-config.js is gitignored (located in js/config/).
//
//  For local development:
//    1. Copy this file to js/config/firebase-config.js (gitignored)
//    2. Fill in your real values from the Firebase Console:
//       https://console.firebase.google.com → your project → Project settings
//    3. Never commit firebase-config.js
//
//  GitHub Actions secrets to add (repo → Settings → Secrets → Actions):
//    FIREBASE_API_KEY
//    FIREBASE_AUTH_DOMAIN
//    FIREBASE_DATABASE_URL
//    FIREBASE_PROJECT_ID
//    FIREBASE_STORAGE_BUCKET
//    FIREBASE_MESSAGING_SENDER_ID
//    FIREBASE_APP_ID
// ═══════════════════════════════════════════════════════════════════

const FIREBASE_CONFIG = {
    apiKey:            "YOUR_API_KEY",
    authDomain:        "YOUR_AUTH_DOMAIN",
    databaseURL:       "YOUR_DATABASE_URL",
    projectId:         "YOUR_PROJECT_ID",
    storageBucket:     "YOUR_STORAGE_BUCKET",
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    appId:             "YOUR_APP_ID"
};

window.FIREBASE_READY = FIREBASE_CONFIG.apiKey !== "YOUR_API_KEY";

if (window.FIREBASE_READY && !firebase.apps.length) {
    firebase.initializeApp(FIREBASE_CONFIG);
}
