name: Deploy Website to Porkbun

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # This will trigger the deployment when code is pushed to the 'main' branch

# Define the jobs that run in this workflow
jobs:
  deploy:
    runs-on: ubuntu-latest  # The operating system for the runner
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # This action checks out your code so the next steps can use it


      # Step 2: Post-deployment confirmation (optional)
      - name: Deployment Confirmation
        run: echo "Deployment to Porkbun successful!"
